name: code_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any       

  cupertino_icons: ^1.0.8
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  shared_preferences: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  generate: true

  uses-material-design: true