name: code_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any       

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  path: ^1.9.0
  file_picker: ^8.1.7
  provider: ^6.1.2
  re_editor:
    path: packages/re_editor
  re_highlight: ^0.0.3
  permission_handler: ^13.0.2
  path_provider: ^2.1.5
  archive: ^3.6.1
  xterm: ^4.0.0
  flutter_pty: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/distros/
    - assets/certs/
    - assets/shims/x86_64/
    - assets/shims/arm64-v8a/
    - assets/icons/distros/

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMonoNerdFontMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMonoNerdFontMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMonoNerdFontMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMonoNerdFontMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCodeNerdFontMono-Regular.ttf
        - asset: assets/fonts/FiraCodeNerdFontMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCodeNerdFontMono-Bold.ttf
          weight: 700